**Importing Libraries**

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv('/content/car_purchasing.csv', encoding='latin1')

df.head()

,customer name,customer e-mail,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Martina Avila,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,eu.dolor@diam.co.uk,Belize,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,Jade Cunningham,malesuada@dignissim.com,Cook Islands,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,Cedric Leach,felis.ullamcorper.viverra@egetmollislectus.net,Brazil,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248

In [12]:
for col in df.columns:
    print(repr(col))

'customer name'
'customer e-mail'
'country'
'gender'
'age'
'annual Salary'
'credit card debt'
'net worth'
'car purchase amount'

In [13]:
df.columns = df.columns.str.strip()

In [14]:
df.drop(
    columns=[
        'customer name',
        'customer e-mail',
        'country',
        'credit card debt',
        'net worth',
        'gender'
    ],
    inplace=True
)

In [15]:
df.head()

         age  annual Salary  car purchase amount
0  41.851720    62812.09301          35321.45877
1  40.870623    66646.89292          45115.52566
2  43.152897    53798.55112          42925.70921
3  58.271369    79370.03798          67422.36313
4  57.313749    59729.15130          55915.46248

In [16]:
df.rename(
    columns={
        'age': 'Age',
        'annual Salary': 'Salary',
        'car purchase amount': 'Buy'
    },
    inplace=True
)

df

           Age       Salary          Buy
0    41.851720  62812.09301  35321.45877
1    40.870623  66646.89292  45115.52566
2    43.152897  53798.55112  42925.70921
3    58.271369  79370.03798  67422.36313
4    57.313749  59729.15130  55915.46248
..         ...          ...          ...
495  41.462515  71942.40291  48901.44342
496  37.642000  56039.49793  31491.41457
497  53.943497  68888.77805  64147.28888
498  59.160509  49811.99062  45442.15353
499  46.731152  61370.67766  45107.22566

[500 rows x 3 columns]

In [28]:
df['Buy'] = (df['Buy'] > df['Buy'].median()).astype(int)

**Basic Operation**

In [29]:
df.shape

(500, 3)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     500 non-null    float64
 1   Salary  500 non-null    float64
 2   Buy     500 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 11.8 KB

In [31]:
df.describe()

              Age         Salary         Buy
count  500.000000     500.000000  500.000000
mean    46.241674   62127.239608    0.500000
std      7.978862   11703.378228    0.500501
min     20.000000   20000.000000    0.000000
25%     40.949969   54391.977195    0.000000
50%     46.049901   62915.497035    0.500000
75%     51.612263   70117.862005    1.000000
max     70.000000  100000.000000    1.000000

In [32]:
df.isnull().sum()

Age       0
Salary    0
Buy       0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

**Segegate Dataset into X, Y**

In [34]:
x= df.iloc[:,:-1]

x.head()

         Age       Salary
0  41.851720  62812.09301
1  40.870623  66646.89292
2  43.152897  53798.55112
3  58.271369  79370.03798
4  57.313749  59729.15130

In [35]:
y= df.iloc[:, -1]

y.head()

0    0
1    1
2    0
3    1
4    1
Name: Buy, dtype: int64

**Split Dataset**

In [36]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.25, random_state=0)

**Feature Scalling**

In [37]:
from sklearn.preprocessing import StandardScaler

sc= StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

**Model Training**

In [38]:
from sklearn.linear_model import LogisticRegression

model= LogisticRegression(random_state=0)
model.fit(x_train, y_train)

LogisticRegression(random_state=0)

**Prediction for new Customer**

In [39]:
age= int(input("Enter New Customers Age: "))
salary= int(input("Enter New Customers Salary: "))
newCust= [[age, salary]]
result= model.predict(sc.transform(newCust))
print(result)

if result==1:
  print("Customer will Buy")
else:
  print("Customer will not Buy")

Enter New Customers Age: 39
Enter New Customers Salary: 55000
[0]
Customer will not Buy

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

**Prediction for all test data**

In [40]:
y_pred= model.predict(x_test)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm= confusion_matrix(y_test, y_pred)
print("Confusion Matrix: ")
print(cm)

print('Accuracy of the model: {0}%'. format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix:
[[50 11]
 [ 8 56]]
Accuracy of the model: 84.8%